name: CI

on:
  push:
    branches: [ master ]
#     paths:
#       - 'packages/server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          
      # Usar cache do yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      # Instalar dependencias do yarn
      - name: Install dependencies
        run: yarn
        
      # Executar build
      - name: Run build
        run: yarn build     
      
      # Copiar pasta /dist para Digital Ocean
      - name: Copy dist folder to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/WeatherHub"
          
      # Executar yarn na Digital Ocean
      - name: Install dependencies on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/WeatherHub
            yarn
        
      
      # Executar as migrations do Typeorm
#       - name: Run typeorm migrations
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           port: ${{ secrets.SSH_PORT }}
#           key: ${{ secrets.SSH_KEY }}
#           script: |
#             cd ~/app/WeatherHub/packages/server
#             ./node_modules/.bin/typeorm migration:run
      
      # Restart no servidor Node.js
      - name: Restart server node.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: pm2 restart weatherhub-api
